import type { GitHubData } from "./github";

export const mockGitHubData: GitHubData = {
  user: {
    login: "toaandri",
    name: "ANDRIANARIJERY Toaviniaina Maharavo",
    avatar_url: "/assets/images/profile-photo.png",
    html_url: "https://github.com/toaandri",
    bio: "Software developer based in Antananarivo, Madagascar. I design and build interactive frontends, complex backends, and robust database architectures.",
    blog: "",
    location: "Antananarivo, Madagascar",
    followers: 6,
    following: 6,
    public_repos: 12,
    created_at: "2024-11-12T00:00:00Z",
    twitter_username: null,
  },
  repos: [
    {
      id: 1,
      name: "MITANEKO",
      full_name: "toaandri/MITANEKO",
      html_url: "https://github.com/toaandri/MITANEKO",
      description: "Participatory urban governance platform — citizens report city issues, community votes to prioritize, local authorities track resolution actions",
      language: "TypeScript",
      stargazers_count: 1,
      forks_count: 0,
      watchers_count: 1,
      topics: ["typescript", "urban-governance", "participatory", "madagascar"],
      updated_at: "2026-05-20T00:00:00Z",
      pushed_at: "2026-05-20T00:00:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 45000, SQL: 8000, HTML: 3000 },
    },
    {
      id: 2,
      name: "M-E-kaly",
      full_name: "toaandri/M-E-kaly",
      html_url: "https://github.com/toaandri/M-E-kaly",
      description: "Full-stack food delivery platform — customer & driver mobile apps, vendor back-office, admin dashboard, phone + OTP auth, Mobile Money payments",
      language: "TypeScript",
      stargazers_count: 0,
      forks_count: 0,
      watchers_count: 0,
      topics: ["typescript", "food-delivery", "react-native", "expo", "full-stack"],
      updated_at: "2026-07-15T00:00:00Z",
      pushed_at: "2026-07-15T00:00:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 52000, SQL: 6000, CSS: 2000 },
    },
    {
      id: 3,
      name: "Projet-transversal-Anamboatra-L2",
      full_name: "toaandri/Projet-transversal-Anamboatra-L2",
      html_url: "https://github.com/toaandri/Projet-transversal-Anamboatra-L2",
      description: "Full-stack platform — citizen web app, staff dashboard & mobile field app with real-time updates",
      language: "TypeScript",
      stargazers_count: 0,
      forks_count: 0,
      watchers_count: 0,
      topics: ["typescript", "full-stack", "real-time", "react", "socketio"],
      updated_at: "2026-04-20T00:00:00Z",
      pushed_at: "2026-04-20T00:00:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 38000, SQL: 5000, HTML: 2000 },
    },
    {
      id: 4,
      name: "Tantsaha-Connect",
      full_name: "toaandri/Tantsaha-Connect",
      html_url: "https://github.com/toaandri/Tantsaha-Connect",
      description: "Platform connecting farmers — 'Tantsaha' means farmer in Malagasy",
      language: "JavaScript",
      stargazers_count: 0,
      forks_count: 0,
      watchers_count: 0,
      topics: ["javascript", "react", "agriculture", "madagascar"],
      updated_at: "2026-03-10T00:00:00Z",
      pushed_at: "2026-03-10T00:00:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { JavaScript: 15000, HTML: 3000, CSS: 2000 },
    },
    {
      id: 5,
      name: "BTP-site-",
      full_name: "toaandri/BTP-site-",
      html_url: "https://github.com/toaandri/BTP-site-",
      description: "Website for the building & public works (BTP) sector",
      language: "TypeScript",
      stargazers_count: 0,
      forks_count: 0,
      watchers_count: 0,
      topics: ["typescript", "btp", "construction", "website"],
      updated_at: "2026-07-10T00:00:00Z",
      pushed_at: "2026-07-10T00:00:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 12000, CSS: 3000, HTML: 2000 },
    },
  ],
  languages: [
    { name: "TypeScript", bytes: 147000, percentage: 45.2, color: "#3178c6" },
    { name: "JavaScript", bytes: 33000, percentage: 10.2, color: "#f1e05a" },
    { name: "Java", bytes: 45000, percentage: 13.9, color: "#b07219" },
    { name: "Python", bytes: 28000, percentage: 8.6, color: "#3572A5" },
    { name: "PHP", bytes: 18000, percentage: 5.5, color: "#4F5D95" },
    { name: "SQL", bytes: 19000, percentage: 5.9, color: "#a8a29e" },
    { name: "HTML", bytes: 10000, percentage: 3.1, color: "#e34c26" },
    { name: "CSS", bytes: 8000, percentage: 2.5, color: "#563d7c" },
  ],
  totalStars: 1,
  lastUpdated: new Date().toISOString(),
};

export function getMockGitHubData(): GitHubData {
  return {
    ...mockGitHubData,
    lastUpdated: new Date().toISOString(),
  };
}