import type { GitHubData } from "./github";

export const mockGitHubData: GitHubData = {
  user: {
    login: "toaandri",
    name: "Maharavo Andrianarijery",
    avatar_url: "https://github.com/toaandri.png",
    html_url: "https://github.com/toaandri",
    bio: "Software Engineering Student from Madagascar. Building practical web apps with TypeScript, Java, Python, and whatever else gets the job done.",
    blog: "",
    location: "Madagascar",
    followers: 42,
    following: 18,
    public_repos: 23,
    created_at: "2020-03-15T10:00:00Z",
    twitter_username: null,
  },
  repos: [
    {
      id: 1,
      name: "portfolio",
      full_name: "toaandri/portfolio",
      html_url: "https://github.com/toaandri/portfolio",
      description: "Personal portfolio built with React, Vite, and Framer Motion",
      language: "TypeScript",
      stargazers_count: 12,
      forks_count: 3,
      watchers_count: 12,
      topics: ["react", "typescript", "vite", "framer-motion", "portfolio"],
      updated_at: "2025-01-15T14:30:00Z",
      pushed_at: "2025-01-15T14:30:00Z",
      homepage: "https://toaandri.dev",
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 45000, CSS: 12000, HTML: 8000 },
    },
    {
      id: 2,
      name: "mitaneko",
      full_name: "toaandri/mitaneko",
      html_url: "https://github.com/toaandri/mitaneko",
      description: "MITANEKO platform for Orange Digital Center POESAM - Madagascar tech challenge",
      language: "Java",
      stargazers_count: 8,
      forks_count: 2,
      watchers_count: 8,
      topics: ["java", "spring-boot", "postgresql", "madagascar", "poesam"],
      updated_at: "2024-11-20T09:15:00Z",
      pushed_at: "2024-11-20T09:15:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { Java: 65000, SQL: 15000, HTML: 5000 },
    },
    {
      id: 3,
      name: "task-manager-api",
      full_name: "toaandri/task-manager-api",
      html_url: "https://github.com/toaandri/task-manager-api",
      description: "RESTful task management API with authentication and real-time updates",
      language: "Python",
      stargazers_count: 15,
      forks_count: 4,
      watchers_count: 15,
      topics: ["python", "fastapi", "postgresql", "redis", "websockets", "api"],
      updated_at: "2024-10-05T16:45:00Z",
      pushed_at: "2024-10-05T16:45:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { Python: 38000, SQL: 8000 },
    },
    {
      id: 4,
      name: "dev-notes",
      full_name: "toaandri/dev-notes",
      html_url: "https://github.com/toaandri/dev-notes",
      description: "Collection of developer notes, snippets, and learning resources",
      language: "TypeScript",
      stargazers_count: 5,
      forks_count: 1,
      watchers_count: 5,
      topics: ["notes", "typescript", "developer-tools", "learning"],
      updated_at: "2024-09-12T11:20:00Z",
      pushed_at: "2024-09-12T11:20:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { TypeScript: 22000, Markdown: 15000, CSS: 5000 },
    },
    {
      id: 5,
      name: "weather-dashboard",
      full_name: "toaandri/weather-dashboard",
      html_url: "https://github.com/toaandri/weather-dashboard",
      description: "Real-time weather dashboard with geolocation and forecast",
      language: "JavaScript",
      stargazers_count: 7,
      forks_count: 2,
      watchers_count: 7,
      topics: ["javascript", "weather-api", "geolocation", "dashboard"],
      updated_at: "2024-08-30T13:10:00Z",
      pushed_at: "2024-08-30T13:10:00Z",
      homepage: null,
      default_branch: "main",
      fork: false,
      languages: { JavaScript: 18000, HTML: 6000, CSS: 4000 },
    },
  ],
  languages: [
    { name: "TypeScript", bytes: 85000, percentage: 38.2, color: "#3178c6" },
    { name: "Java", bytes: 65000, percentage: 29.2, color: "#b07219" },
    { name: "Python", bytes: 38000, percentage: 17.1, color: "#3572A5" },
    { name: "JavaScript", bytes: 18000, percentage: 8.1, color: "#f1e05a" },
    { name: "CSS", bytes: 9000, percentage: 4.0, color: "#563d7c" },
    { name: "HTML", bytes: 7000, percentage: 3.1, color: "#e34c26" },
    { name: "SQL", bytes: 5000, percentage: 2.2, color: "#a8a29e" },
  ],
  totalStars: 47,
  lastUpdated: new Date().toISOString(),
};

export function getMockGitHubData(): GitHubData {
  return {
    ...mockGitHubData,
    lastUpdated: new Date().toISOString(),
  };
}